#!/usr/bin/env python

import rospy
from sensor_msgs.msg import Image
from cv_bridge import CvBridge
import cv2

def image_callback(msg):
    bridge = CvBridge()
    cv_image = bridge.imgmsg_to_cv2(msg, desired_encoding="bgr8")
    print("I got it")

    # Process cv_image as needed
    cv2.imshow("Received Image", cv_image)
    cv2.waitKey(1)

def receiver_node():
    rospy.init_node('image_receiver', anonymous=True)

    image_sub = rospy.Subscriber('image_topic', Image, image_callback)
    rospy.spin()

if __name__ == '__main__':
    try:
        receiver_node()
    except rospy.ROSInterruptException:
        pass
